/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/location-picker`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/menu`; params?: Router.UnknownInputParams; } | { pathname: `/notifications`; params?: Router.UnknownInputParams; } | { pathname: `/splash`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/akaun` | `/akaun`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/bantuan` | `/bantuan`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/tempahan` | `/tempahan`; params?: Router.UnknownInputParams; } | { pathname: `/order/quote`; params?: Router.UnknownInputParams; } | { pathname: `/order/chat/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/order/rate/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/order/tracking/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/location-picker`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/menu`; params?: Router.UnknownOutputParams; } | { pathname: `/notifications`; params?: Router.UnknownOutputParams; } | { pathname: `/splash`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/akaun` | `/akaun`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/bantuan` | `/bantuan`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/tempahan` | `/tempahan`; params?: Router.UnknownOutputParams; } | { pathname: `/order/quote`; params?: Router.UnknownOutputParams; } | { pathname: `/order/chat/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/order/rate/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/order/tracking/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/location-picker${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/menu${`?${string}` | `#${string}` | ''}` | `/notifications${`?${string}` | `#${string}` | ''}` | `/splash${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/akaun${`?${string}` | `#${string}` | ''}` | `/akaun${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/bantuan${`?${string}` | `#${string}` | ''}` | `/bantuan${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/tempahan${`?${string}` | `#${string}` | ''}` | `/tempahan${`?${string}` | `#${string}` | ''}` | `/order/quote${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/location-picker`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/menu`; params?: Router.UnknownInputParams; } | { pathname: `/notifications`; params?: Router.UnknownInputParams; } | { pathname: `/splash`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/akaun` | `/akaun`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/bantuan` | `/bantuan`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/tempahan` | `/tempahan`; params?: Router.UnknownInputParams; } | { pathname: `/order/quote`; params?: Router.UnknownInputParams; } | `/order/chat/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/order/rate/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/order/tracking/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/order/chat/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/order/rate/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/order/tracking/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
