name: Preview

on:
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install EAS CLI globally
        run: npm install -g eas-cli

      - name: Run EAS Update
        run: eas update --auto --project-id bbb1ed02-5bff-4690-95fc-7dfaac95bf6f
        working-directory: ./frontend
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
